-- Generated from assets/data/teacher-assignment-seed.json
-- Source: all semester.txt

insert into public.feedback_settings (id, allow_anonymous_feedback, review_window_open, active_term)
values (1, true, true, 'Current Session')
on conflict (id) do update
set allow_anonymous_feedback = excluded.allow_anonymous_feedback,
    review_window_open = excluded.review_window_open,
    active_term = excluded.active_term;

insert into public.teachers_directory (name, designation, email, department, status)
values
  ('Arifa Ferdous', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Barisha Chowdhury', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Bebak More', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Dr. Sinthia Shabnam Mou', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('ECO New Teacher', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Fahmina Zahan', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Foez Ahmed', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Md. Babul Islam', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Md. Moniruzzaman Kiron', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Mehedi Hasan Shakil', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Most. Afshara Tasnim Ritu', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Sajeeb Kumar Ray', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Shakil Hossan', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Syeda Tamanna Alam Monisha', 'Lecturer', NULL, 'Computer Science and Engineering', 'active'),
  ('Tahrima Sayem Sowa', 'Lecturer', NULL, 'Computer Science and Engineering', 'active')
on conflict do nothing;

with assignment_seed (teacher_name, course_code, course_title, semester, section, academic_term, is_active) as (
values
  ('Shorav Paul', 'CHE 1161', 'Chemistry', '1st Semester', 'A', '', true),
  ('Md. Nour Noby', 'CSE 1100', 'Structured Programming Language', '1st Semester', 'A', '', true),
  ('Dr. Jaker Hossain', 'EEE 1131', 'Basic Electrical Circuits', '1st Semester', 'A', '', true),
  ('Mst. Nafia Islam Shishir', 'EEE 1132', 'Basic Electrical Circuits Lab', '1st Semester', 'A', '', true),
  ('Zannatul Mifta', 'EEE 1132', 'Basic Electrical Circuits Lab', '1st Semester', 'A', '', true),
  ('Fahmina Zahan', 'ENG 0002', 'English Fundamentals', '1st Semester', 'A', '', true),
  ('Dr.Md. Abu Bakar PK.', 'MAT 1141', 'Differential and Integral Calculus', '1st Semester', 'A', '', true),
  ('Md. Mizanur Rahman', 'MAT 1141', 'Differential and Integral Calculus', '1st Semester', 'A', '', true),
  ('Dr.Md. Johirul Islam', 'PHY 1151', 'Basic Physics', '1st Semester', 'A', '', true),
  ('Md. Ruhul Amin', 'PHY 1151', 'Basic Physics', '1st Semester', 'A', '', true),
  ('Shorav Paul', 'CHE 1161', 'Chemistry', '1st Semester', 'B', '', true),
  ('Dr.Md. Abu Bakar PK.', 'EEE 1131', 'Basic Electrical Circuits', '1st Semester', 'B', '', true),
  ('Md. Babul Islam', 'EEE 1131', 'Basic Electrical Circuits', '1st Semester', 'B', '', true),
  ('Zannatul Mifta', 'EEE 1132', 'Basic Electrical Circuits Lab', '1st Semester', 'B', '', true),
  ('Fahmina Zahan', 'ENG 0002', 'English Fundamentals', '1st Semester', 'B', '', true),
  ('Dr.Md. Abu Bakar PK.', 'MAT 1141', 'Differential and Integral Calculus', '1st Semester', 'B', '', true),
  ('Md. Mizanur Rahman', 'MAT 1141', 'Differential and Integral Calculus', '1st Semester', 'B', '', true),
  ('Dr.Md. Johirul Islam', 'PHY 1151', 'Basic Physics', '1st Semester', 'B', '', true),
  ('Md. Faruk Hossain, Ph.D.', 'PHY 1151', 'Basic Physics', '1st Semester', 'B', '', true),
  ('Shorav Paul', 'CHE 1161', 'Chemistry', '1st Semester', 'C', '', true),
  ('Md. Nour Noby', 'CSE 1100', 'Structured Programming Language', '1st Semester', 'C', '', true),
  ('Dr.Md. Abu Bakar PK.', 'EEE 1131', 'Basic Electrical Circuits', '1st Semester', 'C', '', true),
  ('Mst. Nafia Islam Shishir', 'EEE 1131', 'Basic Electrical Circuits', '1st Semester', 'C', '', true),
  ('Fahmina Zahan', 'ENG 0002', 'English Fundamentals', '1st Semester', 'C', '', true),
  ('Md. Mizanur Rahman', 'MAT 1141', 'Differential and Integral Calculus', '1st Semester', 'C', '', true),
  ('Dr.Md. Johirul Islam', 'PHY 1151', 'Basic Physics', '1st Semester', 'C', '', true),
  ('Md. Faruk Hossain, Ph.D.', 'PHY 1151', 'Basic Physics', '1st Semester', 'C', '', true),
  ('Md. Ruhul Amin', 'PHY 1152', 'Basic Physics Lab', '1st Semester', 'C', '', true),
  ('Md. Muktar Hossain', 'CSE 1201', 'Object Oriented Programming', '2nd Semester', 'A', '', true),
  ('A.S.M. Delwar Hossain', 'CSE 1202', 'Object Oriented Programming Lab', '2nd Semester', 'A', '', true),
  ('Md. Muktar Hossain', 'CSE 1202', 'Object Oriented Programming Lab', '2nd Semester', 'A', '', true),
  ('Sanjoy Kumar Chakravarty', 'CSE 1203', 'Discrete Mathematics', '2nd Semester', 'A', '', true),
  ('Ipshita Tasnim Raha', 'EEE 1232', 'Electronic Devices and Circuits Lab', '2nd Semester', 'A', '', true),
  ('Mehedi Hasan Shakil', 'EEE 1232', 'Electronic Devices and Circuits Lab', '2nd Semester', 'A', '', true),
  ('Md. Mizanur Rahman', 'MAT 1241', 'Coordinate Geometry and Vector Analysis', '2nd Semester', 'A', '', true),
  ('Most. Afshara Tasnim Ritu', 'BAN 0001', 'History of the Emergence of Bangladesh', '2nd Semester', 'B', '', true),
  ('Md. Muktar Hossain', 'CSE 1201', 'Object Oriented Programming', '2nd Semester', 'B', '', true),
  ('Md. Muktar Hossain', 'CSE 1202', 'Object Oriented Programming Lab', '2nd Semester', 'B', '', true),
  ('Tanver Ahmed', 'CSE 1202', 'Object Oriented Programming Lab', '2nd Semester', 'B', '', true),
  ('Mehedi Hasan Shakil', 'CSE 1203', 'Discrete Mathematics', '2nd Semester', 'B', '', true),
  ('Dr. Sinthia Shabnam Mou', 'EEE 1231', 'Electronic Devices and Circuits', '2nd Semester', 'B', '', true),
  ('Md. Adnan Sami', 'EEE 1232', 'Electronic Devices and Circuits Lab', '2nd Semester', 'B', '', true),
  ('Md. Alamin Hossain Pappu', 'EEE 1232', 'Electronic Devices and Circuits Lab', '2nd Semester', 'B', '', true),
  ('Md. Mizanur Rahman', 'MAT 1241', 'Coordinate Geometry and Vector Analysis', '2nd Semester', 'B', '', true),
  ('Md. Muktar Hossain', 'CSE 1201', 'Object Oriented Programming', '2nd Semester', 'C', '', true),
  ('Md. Muktar Hossain', 'CSE 1202', 'Object Oriented Programming Lab', '2nd Semester', 'C', '', true),
  ('Mohammad Kasedullah', 'CSE 1202', 'Object Oriented Programming Lab', '2nd Semester', 'C', '', true),
  ('Umme Rumman', 'CSE 1203', 'Discrete Mathematics', '2nd Semester', 'C', '', true),
  ('Ipshita Tasnim Raha', 'EEE 1231', 'Electronic Devices and Circuits', '2nd Semester', 'C', '', true),
  ('Ipshita Tasnim Raha', 'EEE 1232', 'Electronic Devices and Circuits Lab', '2nd Semester', 'C', '', true),
  ('Md. Alamin Hossain Pappu', 'EEE 1232', 'Electronic Devices and Circuits Lab', '2nd Semester', 'C', '', true),
  ('Md. Mizanur Rahman', 'MAT 1241', 'Coordinate Geometry and Vector Analysis', '2nd Semester', 'C', '', true),
  ('A.S.M. Delwar Hossain', 'CSE 2101', 'Object Oriented Design and Design Patterns', '3rd Semester', 'A', '', true),
  ('A.S.M. Delwar Hossain', 'CSE 2102', 'Object Oriented Design and Design Patterns Lab', '3rd Semester', 'A', '', true),
  ('Md. Nour Noby', 'CSE 2102', 'Object Oriented Design and Design Patterns Lab', '3rd Semester', 'A', '', true),
  ('Dr. Md. Golam Rashed', 'CSE 2103', 'Data Structures', '3rd Semester', 'A', '', true),
  ('Mohammad Kasedullah', 'CSE 2104', 'Data Structures Lab', '3rd Semester', 'A', '', true),
  ('Samira Tareque', 'CSE 2104', 'Data Structures Lab', '3rd Semester', 'A', '', true),
  ('D.M. Asadujjaman', 'CSE 2105', 'Digital System Design', '3rd Semester', 'A', '', true),
  ('D.M. Asadujjaman', 'CSE 2106', 'Digital System Design Lab', '3rd Semester', 'A', '', true),
  ('Mst. Mazeda Noor Tasnim', 'CSE 2106', 'Digital System Design Lab', '3rd Semester', 'A', '', true),
  ('Anupoma Barman Shetu', 'MAT 2141', 'Differential Equations', '3rd Semester', 'A', '', true),
  ('A.S.M. Delwar Hossain', 'CSE 2101', 'Object Oriented Design and Design Patterns', '3rd Semester', 'B', '', true),
  ('A.S.M. Delwar Hossain', 'CSE 2102', 'Object Oriented Design and Design Patterns Lab', '3rd Semester', 'B', '', true),
  ('Mohammad Faisal Al-Naser', 'CSE 2102', 'Object Oriented Design and Design Patterns Lab', '3rd Semester', 'B', '', true),
  ('Samira Tareque', 'CSE 2103', 'Data Structures', '3rd Semester', 'B', '', true),
  ('D.M. Asadujjaman', 'CSE 2104', 'Data Structures Lab', '3rd Semester', 'B', '', true),
  ('Samira Tareque', 'CSE 2104', 'Data Structures Lab', '3rd Semester', 'B', '', true),
  ('D.M. Asadujjaman', 'CSE 2105', 'Digital System Design', '3rd Semester', 'B', '', true),
  ('D.M. Asadujjaman', 'CSE 2106', 'Digital System Design Lab', '3rd Semester', 'B', '', true),
  ('Mst. Mazeda Noor Tasnim', 'CSE 2106', 'Digital System Design Lab', '3rd Semester', 'B', '', true),
  ('Anupoma Barman Shetu', 'MAT 2141', 'Differential Equations', '3rd Semester', 'B', '', true),
  ('A.S.M. Delwar Hossain', 'CSE 2101', 'Object Oriented Design and Design Patterns', '3rd Semester', 'C', '', true),
  ('A.S.M. Delwar Hossain', 'CSE 2102', 'Object Oriented Design and Design Patterns Lab', '3rd Semester', 'C', '', true),
  ('Mohammad Faisal Al-Naser', 'CSE 2102', 'Object Oriented Design and Design Patterns Lab', '3rd Semester', 'C', '', true),
  ('Samira Tareque', 'CSE 2103', 'Data Structures', '3rd Semester', 'C', '', true),
  ('Israt Jahan Rinky', 'CSE 2104', 'Data Structures Lab', '3rd Semester', 'C', '', true),
  ('Samira Tareque', 'CSE 2104', 'Data Structures Lab', '3rd Semester', 'C', '', true),
  ('D.M. Asadujjaman', 'CSE 2105', 'Digital System Design', '3rd Semester', 'C', '', true),
  ('D.M. Asadujjaman', 'CSE 2106', 'Digital System Design Lab', '3rd Semester', 'C', '', true),
  ('Mst. Mazeda Noor Tasnim', 'CSE 2106', 'Digital System Design Lab', '3rd Semester', 'C', '', true),
  ('Anupoma Barman Shetu', 'MAT 2141', 'Differential Equations', '3rd Semester', 'C', '', true),
  ('Mohammad Kasedullah', 'CSE 2201', 'Software Engineering and System Analysis', '4th Semester', 'A', '', true),
  ('Sumaiya Tasnim', 'CSE 2203', 'Computer Algorithms', '4th Semester', 'A', '', true),
  ('Samira Tareque', 'CSE 2204', 'Computer Algorithms Lab', '4th Semester', 'A', '', true),
  ('Sumaiya Tasnim', 'CSE 2204', 'Computer Algorithms Lab', '4th Semester', 'A', '', true),
  ('Adrita Alam', 'CSE 2205', 'Numerical Methods', '4th Semester', 'A', '', true),
  ('Adrita Alam', 'CSE 2206', 'Numerical Methods Lab', '4th Semester', 'A', '', true),
  ('Md. Fayzul Islam', 'CSE 2206', 'Numerical Methods Lab', '4th Semester', 'A', '', true),
  ('Prof.Dr. Boshir Ahmed', 'CSE 2207', 'Computer Networks', '4th Semester', 'A', '', true),
  ('Arshad Wasif', 'CSE 2208', 'Computer Networks Lab', '4th Semester', 'A', '', true),
  ('Umme Rumman', 'CSE 2208', 'Computer Networks Lab', '4th Semester', 'A', '', true),
  ('Dr. Ahammad Hossain', 'MAT 2241', 'Linear Algebra and Complex Variables', '4th Semester', 'A', '', true),
  ('Mohammad Kasedullah', 'CSE 2201', 'Software Engineering and System Analysis', '4th Semester', 'B', '', true),
  ('Dr. Md. Iqbal Aziz Khan', 'CSE 2203', 'Computer Algorithms', '4th Semester', 'B', '', true),
  ('Afroza Islam', 'CSE 2204', 'Computer Algorithms Lab', '4th Semester', 'B', '', true),
  ('Nafia Islam', 'CSE 2204', 'Computer Algorithms Lab', '4th Semester', 'B', '', true),
  ('Adrita Alam', 'CSE 2205', 'Numerical Methods', '4th Semester', 'B', '', true),
  ('Adrita Alam', 'CSE 2206', 'Numerical Methods Lab', '4th Semester', 'B', '', true),
  ('Shamim Reza', 'CSE 2206', 'Numerical Methods Lab', '4th Semester', 'B', '', true),
  ('Akib Ikbal', 'CSE 2207', 'Computer Networks', '4th Semester', 'B', '', true),
  ('Akib Ikbal', 'CSE 2208', 'Computer Networks Lab', '4th Semester', 'B', '', true),
  ('Umme Rumman', 'CSE 2208', 'Computer Networks Lab', '4th Semester', 'B', '', true),
  ('Dr. Ahammad Hossain', 'MAT 2241', 'Linear Algebra and Complex Variables', '4th Semester', 'B', '', true),
  ('Mohammad Faisal Al-Naser', 'CSE 2201', 'Software Engineering and System Analysis', '4th Semester', 'C', '', true),
  ('Sumaiya Tasnim', 'CSE 2203', 'Computer Algorithms', '4th Semester', 'C', '', true),
  ('Ipshita Tasnim Raha', 'CSE 2204', 'Computer Algorithms Lab', '4th Semester', 'C', '', true),
  ('Sumaiya Tasnim', 'CSE 2204', 'Computer Algorithms Lab', '4th Semester', 'C', '', true),
  ('Adrita Alam', 'CSE 2205', 'Numerical Methods', '4th Semester', 'C', '', true),
  ('Adrita Alam', 'CSE 2206', 'Numerical Methods Lab', '4th Semester', 'C', '', true),
  ('Shamim Reza', 'CSE 2206', 'Numerical Methods Lab', '4th Semester', 'C', '', true),
  ('Akib Ikbal', 'CSE 2207', 'Computer Networks', '4th Semester', 'C', '', true),
  ('Akib Ikbal', 'CSE 2208', 'Computer Networks Lab', '4th Semester', 'C', '', true),
  ('Umme Rumman', 'CSE 2208', 'Computer Networks Lab', '4th Semester', 'C', '', true),
  ('Arun Kumar Sikder', 'MAT 2241', 'Linear Algebra and Complex Variables', '4th Semester', 'C', '', true),
  ('Ayesha Akter Lima', 'CSE 3101', 'Computer Graphics', '5th Semester', 'A', '', true),
  ('Ayesha Akter Lima', 'CSE 3102', 'Computer Graphics Lab', '5th Semester', 'A', '', true),
  ('Mst. Jannatul Ferdous', 'CSE 3102', 'Computer Graphics Lab', '5th Semester', 'A', '', true),
  ('Shamim Ahmad', 'CSE 3103', 'Database Management System', '5th Semester', 'A', '', true),
  ('Afifa Tasneem Quanita', 'CSE 3104', 'Database Management System Lab', '5th Semester', 'A', '', true),
  ('Sumaia Rahman', 'CSE 3104', 'Database Management System Lab', '5th Semester', 'A', '', true),
  ('Md. Ruhul Amin', 'CSE 3106', 'Computer Architecture Lab', '5th Semester', 'A', '', true),
  ('Protik Chakroborty', 'CSE 3106', 'Computer Architecture Lab', '5th Semester', 'A', '', true),
  ('Zannatul Mifta', 'CSE 3107', 'Communication Engineering', '5th Semester', 'A', '', true),
  ('Prof. A.H.M. Rahmatullah Imon, Ph.D.', 'MAT 3141', 'Applied Statistics and Probability', '5th Semester', 'A', '', true),
  ('Ayesha Akter Lima', 'CSE 3101', 'Computer Graphics', '5th Semester', 'B', '', true),
  ('Ayesha Akter Lima', 'CSE 3102', 'Computer Graphics Lab', '5th Semester', 'B', '', true),
  ('Mst. Jannatul Ferdous', 'CSE 3102', 'Computer Graphics Lab', '5th Semester', 'B', '', true),
  ('Shamim Ahmad', 'CSE 3103', 'Database Management System', '5th Semester', 'B', '', true),
  ('Afifa Tasneem Quanita', 'CSE 3104', 'Database Management System Lab', '5th Semester', 'B', '', true),
  ('Sumaia Rahman', 'CSE 3104', 'Database Management System Lab', '5th Semester', 'B', '', true),
  ('Protik Chakroborty', 'CSE 3105', 'Computer Architecture', '5th Semester', 'B', '', true),
  ('Md. Ruhul Amin', 'CSE 3106', 'Computer Architecture Lab', '5th Semester', 'B', '', true),
  ('Protik Chakroborty', 'CSE 3106', 'Computer Architecture Lab', '5th Semester', 'B', '', true),
  ('Foez Ahmed', 'CSE 3107', 'Communication Engineering', '5th Semester', 'B', '', true),
  ('Dr. Ahammad Hossain', 'MAT 3141', 'Applied Statistics and Probability', '5th Semester', 'B', '', true),
  ('Ayesha Akter Lima', 'CSE 3012', 'Computer Graphics Lab', '5th Semester', 'C', '', true),
  ('Zuairia Raisa Bintay Makin', 'CSE 3012', 'Computer Graphics Lab', '5th Semester', 'C', '', true),
  ('Ayesha Akter Lima', 'CSE 3101', 'Computer Graphics', '5th Semester', 'C', '', true),
  ('Afifa Tasneem Quanita', 'CSE 3103', 'Database Management System', '5th Semester', 'C', '', true),
  ('Afifa Tasneem Quanita', 'CSE 3104', 'Database Management System Lab', '5th Semester', 'C', '', true),
  ('Sumaia Rahman', 'CSE 3104', 'Database Management System Lab', '5th Semester', 'C', '', true),
  ('Protik Chakroborty', 'CSE 3105', 'Computer Architecture', '5th Semester', 'C', '', true),
  ('Mohsiul Mumit Alik', 'CSE 3106', 'Computer Architecture Lab', '5th Semester', 'C', '', true),
  ('Protik Chakroborty', 'CSE 3106', 'Computer Architecture Lab', '5th Semester', 'C', '', true),
  ('Arifa Ferdous', 'CSE 3107', 'Communication Engineering', '5th Semester', 'C', '', true),
  ('Dr. Ahammad Hossain', 'MAT 3141', 'Applied Statistics and Probability', '5th Semester', 'C', '', true),
  ('Sumaia Rahman', 'CSE 3201', 'Theory of Computation and Compiler Design', '6th Semester', 'A', '', true),
  ('Rokaiya Tasnim', 'CSE 3203', 'Operating System and System Programming', '6th Semester', 'A', '', true),
  ('Md. Rakibul Islam', 'CSE 3204', 'Operating System and System Programming Lab', '6th Semester', 'A', '', true),
  ('Rokaiya Tasnim', 'CSE 3204', 'Operating System and System Programming Lab', '6th Semester', 'A', '', true),
  ('Tahrima Sayem Sowa', 'CSE 3205', 'Microprocessor and Assembly Language', '6th Semester', 'A', '', true),
  ('Md. Alamin Hossain Pappu', 'CSE 3206', 'Microprocessor and Assembly Language Lab', '6th Semester', 'A', '', true),
  ('Tahrima Sayem Sowa', 'CSE 3206', 'Microprocessor and Assembly Language Lab', '6th Semester', 'A', '', true),
  ('Shamim Reza', 'CSE 3207', 'Digital Signal Processing', '6th Semester', 'A', '', true),
  ('Mst. Jannatul Ferdous', 'CSE 3208', 'Digital Signal Processing Lab', '6th Semester', 'A', '', true),
  ('Shamim Reza', 'CSE 3208', 'Digital Signal Processing Lab', '6th Semester', 'A', '', true),
  ('Mehedi Hasan Shakil', 'CSE 3209', 'E-commerce and Web Programming', '6th Semester', 'A', '', true),
  ('Akib Ikbal', 'CSE 3210', 'E-commerce and Web Programming Project Lab', '6th Semester', 'A', '', true),
  ('Mehedi Hasan Shakil', 'CSE 3210', 'E-commerce and Web Programming Project Lab', '6th Semester', 'A', '', true),
  ('ECO New Teacher', 'ECO 3271', 'Engineering Economics', '6th Semester', 'A', '', true),
  ('Israt Jahan Rinky', 'CSE 3201', 'Theory of Computation and Compiler Design', '6th Semester', 'B', '', true),
  ('Rokaiya Tasnim', 'CSE 3203', 'Operating System and System Programming', '6th Semester', 'B', '', true),
  ('Md. Rakibul Islam', 'CSE 3204', 'Operating System and System Programming Lab', '6th Semester', 'B', '', true),
  ('Rokaiya Tasnim', 'CSE 3204', 'Operating System and System Programming Lab', '6th Semester', 'B', '', true),
  ('Tahrima Sayem Sowa', 'CSE 3205', 'Microprocessor and Assembly Language', '6th Semester', 'B', '', true),
  ('Md. Alamin Hossain Pappu', 'CSE 3206', 'Microprocessor and Assembly Language Lab', '6th Semester', 'B', '', true),
  ('Tahrima Sayem Sowa', 'CSE 3206', 'Microprocessor and Assembly Language Lab', '6th Semester', 'B', '', true),
  ('Mst. Mazeda Noor Tasnim', 'CSE 3207', 'Digital Signal Processing', '6th Semester', 'B', '', true),
  ('Mst. Mazeda Noor Tasnim', 'CSE 3208', 'Digital Signal Processing Lab', '6th Semester', 'B', '', true),
  ('Zuairia Raisa Bintay Makin', 'CSE 3208', 'Digital Signal Processing Lab', '6th Semester', 'B', '', true),
  ('Mehedi Hasan Shakil', 'CSE 3209', 'E-commerce and Web Programming', '6th Semester', 'B', '', true),
  ('Akib Ikbal', 'CSE 3210', 'E-commerce and Web Programming Project Lab', '6th Semester', 'B', '', true),
  ('Mehedi Hasan Shakil', 'CSE 3210', 'E-commerce and Web Programming Project Lab', '6th Semester', 'B', '', true),
  ('ECO New Teacher', 'ECO 3271', 'Engineering Economics', '6th Semester', 'B', '', true),
  ('Israt Jahan Rinky', 'CSE 3201', 'Theory of Computation and Compiler Design', '6th Semester', 'C', '', true),
  ('Rokaiya Tasnim', 'CSE 3203', 'Operating System and System Programming', '6th Semester', 'C', '', true),
  ('Md. Rakibul Islam', 'CSE 3204', 'Operating System and System Programming Lab', '6th Semester', 'C', '', true),
  ('Rokaiya Tasnim', 'CSE 3204', 'Operating System and System Programming Lab', '6th Semester', 'C', '', true),
  ('Tahrima Sayem Sowa', 'CSE 3205', 'Microprocessor and Assembly Language', '6th Semester', 'C', '', true),
  ('Md. Mahfujur Rahman', 'CSE 3206', 'Microprocessor and Assembly Language Lab', '6th Semester', 'C', '', true),
  ('Tahrima Sayem Sowa', 'CSE 3206', 'Microprocessor and Assembly Language Lab', '6th Semester', 'C', '', true),
  ('Shamim Reza', 'CSE 3207', 'Digital Signal Processing', '6th Semester', 'C', '', true),
  ('Barisha Chowdhury', 'CSE 3209', 'E-commerce and Web Programming', '6th Semester', 'C', '', true),
  ('Barisha Chowdhury', 'CSE 3210', 'E-commerce and Web Programming Project Lab', '6th Semester', 'C', '', true),
  ('Israt Jahan Rinky', 'CSE 3210', 'E-commerce and Web Programming Project Lab', '6th Semester', 'C', '', true),
  ('ECO New Teacher', 'ECO 3271', 'Engineering Economics', '6th Semester', 'C', '', true),
  ('Bebak More', 'ACC 4171', 'Industrial Management and Accountancy', '7th Semester', 'A', '', true),
  ('Md. Mahfujur Rahman', 'CSE 4101', 'Artificial Intelligence', '7th Semester', 'A', '', true),
  ('Md. Mahfujur Rahman', 'CSE 4102', 'Artificial Intelligence Lab', '7th Semester', 'A', '', true),
  ('Mst. Nafia Islam Shishir', 'CSE 4102', 'Artificial Intelligence Lab', '7th Semester', 'A', '', true),
  ('Md. Taufiq Khan', 'CSE 4103', 'Digital Image Processing', '7th Semester', 'A', '', true),
  ('Md. Taufiq Khan', 'CSE 4104', 'Digital Image Processing Lab', '7th Semester', 'A', '', true),
  ('Sajeeb Kumar Ray', 'CSE 4104', 'Digital Image Processing Lab', '7th Semester', 'A', '', true),
  ('Shakil Hossan', 'CSE 4105', 'Engineering Ethics and Environmental Protection', '7th Semester', 'A', '', true),
  ('Dr. Md. Ariful Islam Nahid', 'CSE 4107', 'Microcontroller, Computer Peripherals and Interfacing', '7th Semester', 'A', '', true),
  ('Asim Moin Saad', 'CSE 4108', 'Microcontroller, Computer Peripherals and Interfacing Lab', '7th Semester', 'A', '', true),
  ('Zannatul Mifta', 'CSE 4108', 'Microcontroller, Computer Peripherals and Interfacing Lab', '7th Semester', 'A', '', true),
  ('Israt Jahan Rinky', 'CSE 4122', 'Technical Report Writing', '7th Semester', 'A', '', true),
  ('Rokaiya Tasnim', 'CSE 4122', 'Technical Report Writing', '7th Semester', 'A', '', true),
  ('Md. Moniruzzaman Kiron', 'ACC 4171', 'Industrial Management and Accountancy', '7th Semester', 'B', '', true),
  ('Md. Mahfujur Rahman', 'CSE 4101', 'Artificial Intelligence', '7th Semester', 'B', '', true),
  ('Md. Mahfujur Rahman', 'CSE 4102', 'Artificial Intelligence Lab', '7th Semester', 'B', '', true),
  ('Mst. Nafia Islam Shishir', 'CSE 4102', 'Artificial Intelligence Lab', '7th Semester', 'B', '', true),
  ('Md. Taufiq Khan', 'CSE 4103', 'Digital Image Processing', '7th Semester', 'B', '', true),
  ('Md. Taufiq Khan', 'CSE 4104', 'Digital Image Processing Lab', '7th Semester', 'B', '', true),
  ('Sajeeb Kumar Ray', 'CSE 4104', 'Digital Image Processing Lab', '7th Semester', 'B', '', true),
  ('Shakil Hossan', 'CSE 4105', 'Engineering Ethics and Environmental Protection', '7th Semester', 'B', '', true),
  ('Dr. Md. Johirul Islam', 'CSE 4107', 'Microcontroller, Computer Peripherals and Interfacing', '7th Semester', 'B', '', true),
  ('Mohsiul Mumit Alik', 'CSE 4108', 'Microcontroller, Computer Peripherals and Interfacing Lab', '7th Semester', 'B', '', true),
  ('Zannatul Mifta', 'CSE 4108', 'Microcontroller, Computer Peripherals and Interfacing Lab', '7th Semester', 'B', '', true),
  ('Rokaiya Tasnim', 'CSE 4122', 'Technical Report Writing', '7th Semester', 'B', '', true),
  ('Shakil Hossan', 'CSE 4122', 'Technical Report Writing', '7th Semester', 'B', '', true),
  ('Sajeeb Kumar Ray', 'CSE 423', 'Advanced CSE Course 423', '8th Semester', 'A', '', true),
  ('Md. Jamil Chaudhary', 'CSE 424', 'Advanced CSE Course 424', '8th Semester', 'A', '', true),
  ('Sajeeb Kumar Ray', 'CSE 424', 'Advanced CSE Course 424', '8th Semester', 'A', '', true),
  ('Sushmit Jahan Rose', 'CSE 431', 'Advanced CSE Course 431', '8th Semester', 'A', '', true),
  ('Barisha Chowdhury', 'CSE 432', 'Advanced CSE Course 432', '8th Semester', 'A', '', true),
  ('Sushmit Jahan Rose', 'CSE 432', 'Advanced CSE Course 432', '8th Semester', 'A', '', true),
  ('Md. Shahid Ahammed Shakil', 'CSE 433', 'Advanced CSE Course 433', '8th Semester', 'A', '', true),
  ('Md. Shahid Ahammed Shakil', 'CSE 434', 'Advanced CSE Course 434', '8th Semester', 'A', '', true),
  ('Md. Taufiq Khan', 'CSE 434', 'Advanced CSE Course 434', '8th Semester', 'A', '', true),
  ('Md. Toufikul Islam', 'CSE 435', 'Advanced CSE Course 435', '8th Semester', 'A', '', true),
  ('Md. Toufikul Islam', 'CSE 436', 'Advanced CSE Course 436', '8th Semester', 'A', '', true),
  ('Sumaya Hannan Shova', 'CSE 436', 'Advanced CSE Course 436', '8th Semester', 'A', '', true),
  ('Md. Fatin Ilham', 'CSE 423', 'Advanced CSE Course 423', '8th Semester', 'B', '', true),
  ('Ahmed-Al-Azmain', 'CSE 424', 'Advanced CSE Course 424', '8th Semester', 'B', '', true),
  ('Md. Fatin Ilham', 'CSE 424', 'Advanced CSE Course 424', '8th Semester', 'B', '', true),
  ('Sushmit Jahan Rose', 'CSE 431', 'Advanced CSE Course 431', '8th Semester', 'B', '', true),
  ('Sumaya Hannan Shova', 'CSE 432', 'Advanced CSE Course 432', '8th Semester', 'B', '', true),
  ('Sushmit Jahan Rose', 'CSE 432', 'Advanced CSE Course 432', '8th Semester', 'B', '', true),
  ('Md. Shahid Ahammed Shakil', 'CSE 433', 'Advanced CSE Course 433', '8th Semester', 'B', '', true),
  ('Md. Shahid Ahammed Shakil', 'CSE 434', 'Advanced CSE Course 434', '8th Semester', 'B', '', true),
  ('Mohammad Faisal Al-Naser', 'CSE 434', 'Advanced CSE Course 434', '8th Semester', 'B', '', true),
  ('Md. Khalid Sakib', 'CSE 435', 'Advanced CSE Course 435', '8th Semester', 'B', '', true),
  ('Md. Fatin Ilham', 'CSE 436', 'Advanced CSE Course 436', '8th Semester', 'B', '', true),
  ('Md. Khalid Sakib', 'CSE 436', 'Advanced CSE Course 436', '8th Semester', 'B', '', true),
  ('Md. Fatin Ilham', 'CSE 423', 'Advanced CSE Course 423', '8th Semester', 'C', '', true),
  ('Ahmed-Al-Azmain', 'CSE 424', 'Advanced CSE Course 424', '8th Semester', 'C', '', true),
  ('Md. Fatin Ilham', 'CSE 424', 'Advanced CSE Course 424', '8th Semester', 'C', '', true),
  ('Sushmit Jahan Rose', 'CSE 431', 'Advanced CSE Course 431', '8th Semester', 'C', '', true),
  ('Md. Shahid Ahammed Shakil', 'CSE 433', 'Advanced CSE Course 433', '8th Semester', 'C', '', true),
  ('Ahmed-Al-Azmain', 'CSE 434', 'Advanced CSE Course 434', '8th Semester', 'C', '', true),
  ('Md. Shahid Ahammed Shakil', 'CSE 434', 'Advanced CSE Course 434', '8th Semester', 'C', '', true),
  ('Md. Khalid Sakib', 'CSE 435', 'Advanced CSE Course 435', '8th Semester', 'C', '', true),
  ('Md. Khalid Sakib', 'CSE 436', 'Advanced CSE Course 436', '8th Semester', 'C', '', true),
  ('Sumaya Hannan Shova', 'CSE 436', 'Advanced CSE Course 436', '8th Semester', 'C', '', true),
  ('Ahmed-Al-Azmain', 'CSE 423', 'Advanced CSE Course 423', '9th Semester', 'General', '', true),
  ('Ahmed-Al-Azmain', 'CSE 424', 'Advanced CSE Course 424', '9th Semester', 'General', '', true),
  ('Md. Fatin Ilham', 'CSE 424', 'Advanced CSE Course 424', '9th Semester', 'General', '', true),
  ('Shakil Hossan', 'CSE 431', 'Advanced CSE Course 431', '9th Semester', 'General', '', true),
  ('Arshad Wasif', 'CSE 432', 'Advanced CSE Course 432', '9th Semester', 'General', '', true),
  ('Shakil Hossan', 'CSE 432', 'Advanced CSE Course 432', '9th Semester', 'General', '', true),
  ('Zuairia Raisa Bintay Makin', 'CSE 433', 'Advanced CSE Course 433', '9th Semester', 'General', '', true),
  ('Md. Shahid Ahammed Shakil', 'CSE 434', 'Advanced CSE Course 434', '9th Semester', 'General', '', true),
  ('Syeda Tamanna Alam Monisha', 'CSE 434', 'Advanced CSE Course 434', '9th Semester', 'General', '', true),
  ('Zuairia Raisa Bintay Makin', 'CSE 434', 'Advanced CSE Course 434', '9th Semester', 'General', '', true),
  ('Md. Toufikul Islam', 'CSE 435', 'Advanced CSE Course 435', '9th Semester', 'General', '', true),
  ('Md. Khalid Sakib', 'CSE 436', 'Advanced CSE Course 436', '9th Semester', 'General', '', true),
  ('Md. Toufikul Islam', 'CSE 436', 'Advanced CSE Course 436', '9th Semester', 'General', '', true)
)
insert into public.teacher_assignments (teacher_directory_id, course_code, course_title, semester, section, academic_term, is_active)
select
  td.id,
  s.course_code,
  s.course_title,
  s.semester,
  s.section,
  s.academic_term,
  s.is_active
from assignment_seed s
join public.teachers_directory td
  on public.normalize_lookup(td.name) = public.normalize_lookup(s.teacher_name)
on conflict on constraint teacher_assignments_unique_assignment do nothing;
